
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 19 22:46:34 CET 2019
//----------------------------------------------------

package compiler.syntax;

import java_cup.runtime.Symbol;
import java.util.*;
import es.uned.lsi.compiler.lexical.*;
import es.uned.lsi.compiler.code.*;
import es.uned.lsi.compiler.intermediate.*;
import es.uned.lsi.compiler.semantic.*;
import es.uned.lsi.compiler.semantic.symbol.*;
import es.uned.lsi.compiler.semantic.type.*;
import es.uned.lsi.compiler.syntax.*;
import compiler.CompilerContext;
import compiler.lexical.*;
import compiler.syntax.nonTerminal.*;
import compiler.semantic.*;
import compiler.semantic.symbol.*;
import compiler.semantic.type.*;
import compiler.intermediate.*;
import compiler.code.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Thu Dec 19 22:46:34 CET 2019
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\132\000\002\002\004\000\002\041\002\000\002\002" +
    "\004\000\002\003\012\000\002\004\002\000\002\005\006" +
    "\000\002\005\005\000\002\005\005\000\002\005\005\000" +
    "\002\005\005\000\002\005\004\000\002\005\004\000\002" +
    "\005\004\000\002\005\004\000\002\005\004\000\002\005" +
    "\004\000\002\005\003\000\002\005\003\000\002\005\003" +
    "\000\002\005\003\000\002\005\003\000\002\006\004\000" +
    "\002\007\007\000\002\007\006\000\002\010\003\000\002" +
    "\010\003\000\002\010\003\000\002\011\004\000\002\012" +
    "\007\000\002\012\006\000\002\013\003\000\002\013\003" +
    "\000\002\014\012\000\002\015\004\000\002\016\007\000" +
    "\002\016\006\000\002\017\004\000\002\017\004\000\002" +
    "\017\003\000\002\020\003\000\002\020\003\000\002\021" +
    "\004\000\002\022\004\000\002\022\004\000\002\022\003" +
    "\000\002\022\003\000\002\023\015\000\002\024\017\000" +
    "\002\025\006\000\002\025\005\000\002\026\004\000\002" +
    "\026\005\000\002\026\003\000\002\030\003\000\002\030" +
    "\003\000\002\030\003\000\002\030\003\000\002\030\005" +
    "\000\002\030\005\000\002\030\005\000\002\030\004\000" +
    "\002\030\005\000\002\030\005\000\002\030\005\000\002" +
    "\030\005\000\002\030\006\000\002\030\006\000\002\031" +
    "\004\000\002\031\005\000\002\031\003\000\002\032\003" +
    "\000\002\032\003\000\002\032\003\000\002\032\003\000" +
    "\002\032\003\000\002\032\003\000\002\032\003\000\002" +
    "\033\004\000\002\033\003\000\002\027\005\000\002\034" +
    "\006\000\002\034\011\000\002\035\012\000\002\035\015" +
    "\000\002\036\015\000\002\037\007\000\002\037\007\000" +
    "\002\037\007\000\002\037\006\000\002\040\007" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\324\000\004\024\000\001\002\000\004\002\326\001" +
    "\002\000\004\024\007\001\002\000\004\002\uffff\001\002" +
    "\000\004\054\010\001\002\000\004\044\011\001\002\000" +
    "\014\006\ufffd\007\013\027\014\030\022\032\017\001\002" +
    "\000\012\006\ufff1\027\014\030\022\032\017\001\002\000" +
    "\004\054\307\001\002\000\006\020\235\023\237\001\002" +
    "\000\004\006\uffee\001\002\000\006\006\uffef\027\014\001" +
    "\002\000\010\042\216\044\ufffd\054\220\001\002\000\004" +
    "\006\047\001\002\000\004\006\uffed\001\002\000\004\054" +
    "\027\001\002\000\010\006\ufff0\027\014\032\017\001\002" +
    "\000\004\006\ufff3\001\002\000\006\006\ufff4\027\014\001" +
    "\002\000\004\006\ufff8\001\002\000\004\052\031\001\002" +
    "\000\010\006\uffe6\027\uffe6\032\uffe6\001\002\000\004\033" +
    "\032\001\002\000\004\037\036\001\002\000\004\043\034" +
    "\001\002\000\012\006\uffe4\027\uffe4\032\uffe4\054\027\001" +
    "\002\000\010\006\uffe5\027\uffe5\032\uffe5\001\002\000\004" +
    "\053\037\001\002\000\004\045\040\001\002\000\004\053" +
    "\041\001\002\000\004\040\042\001\002\000\004\010\043" +
    "\001\002\000\006\004\045\013\046\001\002\000\004\043" +
    "\uffe1\001\002\000\016\031\uffe2\036\uffe2\042\uffe2\043\uffe2" +
    "\044\uffe2\054\uffe2\001\002\000\016\031\uffe3\036\uffe3\042" +
    "\uffe3\043\uffe3\044\uffe3\054\uffe3\001\002\000\032\005\052" +
    "\012\071\015\063\016\057\017\ufffd\021\072\022\056\025" +
    "\062\035\055\037\067\053\064\054\066\001\002\000\034" +
    "\005\uffb8\012\uffb8\015\uffb8\016\uffb8\017\uffb8\021\uffb8\022" +
    "\uffb8\025\uffb8\026\uffb8\035\uffb8\037\uffb8\053\uffb8\054\uffb8" +
    "\001\002\000\004\017\214\001\002\000\066\005\uffca\011" +
    "\uffca\012\uffca\014\uffca\015\uffca\016\uffca\017\uffca\021\uffca" +
    "\022\uffca\025\uffca\026\uffca\034\uffca\035\uffca\036\uffca\037" +
    "\uffca\040\uffca\042\uffca\043\uffca\044\uffca\045\uffca\046\uffca" +
    "\047\uffca\050\uffca\051\uffca\053\uffca\054\uffca\001\002\000" +
    "\034\005\uffb9\012\uffb9\015\uffb9\016\uffb9\017\uffb9\021\uffb9" +
    "\022\uffb9\025\uffb9\026\uffb9\035\uffb9\037\uffb9\053\uffb9\054" +
    "\uffb9\001\002\000\046\005\uffbb\012\uffbb\015\uffbb\016\uffbb" +
    "\017\uffbb\021\uffbb\022\uffbb\025\uffbb\026\uffbb\034\103\035" +
    "\uffbb\037\uffbb\046\100\047\102\050\101\051\077\053\uffbb" +
    "\054\uffbb\001\002\000\020\005\052\016\057\021\072\035" +
    "\055\037\067\053\064\054\075\001\002\000\020\005\052" +
    "\016\057\021\072\035\055\037\067\053\064\054\075\001" +
    "\002\000\066\005\uffc9\011\uffc9\012\uffc9\014\uffc9\015\uffc9" +
    "\016\uffc9\017\uffc9\021\uffc9\022\uffc9\025\uffc9\026\uffc9\034" +
    "\uffc9\035\uffc9\036\uffc9\037\uffc9\040\uffc9\042\uffc9\043\uffc9" +
    "\044\uffc9\045\uffc9\046\uffc9\047\uffc9\050\uffc9\051\uffc9\053" +
    "\uffc9\054\uffc9\001\002\000\034\005\052\012\071\015\063" +
    "\016\057\017\ufffd\021\072\022\056\025\062\026\ufffd\035" +
    "\055\037\067\053\064\054\066\001\002\000\034\005\uffb6" +
    "\012\uffb6\015\uffb6\016\uffb6\017\uffb6\021\uffb6\022\uffb6\025" +
    "\uffb6\026\uffb6\035\uffb6\037\uffb6\053\uffb6\054\uffb6\001\002" +
    "\000\020\005\052\016\057\021\072\035\055\037\067\053" +
    "\064\054\075\001\002\000\004\035\146\001\002\000\066" +
    "\005\uffcb\011\uffcb\012\uffcb\014\uffcb\015\uffcb\016\uffcb\017" +
    "\uffcb\021\uffcb\022\uffcb\025\uffcb\026\uffcb\034\uffcb\035\uffcb" +
    "\036\uffcb\037\uffcb\040\uffcb\042\uffcb\043\uffcb\044\uffcb\045" +
    "\uffcb\046\uffcb\047\uffcb\050\uffcb\051\uffcb\053\uffcb\054\uffcb" +
    "\001\002\000\034\005\uffba\012\uffba\015\uffba\016\uffba\017" +
    "\uffba\021\uffba\022\uffba\025\uffba\026\uffba\035\uffba\037\uffba" +
    "\053\uffba\054\uffba\001\002\000\050\005\uffcc\012\uffcc\015" +
    "\uffcc\016\uffcc\017\uffcc\021\uffcc\022\uffcc\025\uffcc\026\uffcc" +
    "\034\uffcc\035\133\037\131\046\uffcc\047\uffcc\050\uffcc\051" +
    "\uffcc\052\132\053\uffcc\054\uffcc\001\002\000\020\005\052" +
    "\016\057\021\072\035\055\037\067\053\064\054\075\001" +
    "\002\000\034\005\uffb5\012\uffb5\015\uffb5\016\uffb5\017\uffb5" +
    "\021\uffb5\022\uffb5\025\uffb5\026\uffb5\035\uffb5\037\uffb5\053" +
    "\uffb5\054\uffb5\001\002\000\020\005\052\016\057\021\072" +
    "\035\055\037\067\053\064\054\075\001\002\000\020\005" +
    "\052\016\057\021\072\035\055\037\067\053\064\054\075" +
    "\001\002\000\034\005\uffb7\012\uffb7\015\uffb7\016\uffb7\017" +
    "\uffb7\021\uffb7\022\uffb7\025\uffb7\026\uffb7\035\uffb7\037\uffb7" +
    "\053\uffb7\054\uffb7\001\002\000\006\017\uffb3\026\uffb3\001" +
    "\002\000\066\005\uffcc\011\uffcc\012\uffcc\014\uffcc\015\uffcc" +
    "\016\uffcc\017\uffcc\021\uffcc\022\uffcc\025\uffcc\026\uffcc\034" +
    "\uffcc\035\112\036\uffcc\037\111\040\uffcc\042\uffcc\043\uffcc" +
    "\044\uffcc\045\uffcc\046\uffcc\047\uffcc\050\uffcc\051\uffcc\053" +
    "\uffcc\054\uffcc\001\002\000\066\005\uffc5\011\uffc5\012\uffc5" +
    "\014\uffc5\015\uffc5\016\uffc5\017\uffc5\021\uffc5\022\uffc5\025" +
    "\uffc5\026\uffc5\034\uffc5\035\uffc5\036\uffc5\037\uffc5\040\uffc5" +
    "\042\uffc5\043\uffc5\044\uffc5\045\uffc5\046\100\047\102\050" +
    "\101\051\077\053\uffc5\054\uffc5\001\002\000\020\005\052" +
    "\016\057\021\072\035\055\037\067\053\064\054\075\001" +
    "\002\000\020\005\052\016\057\021\072\035\055\037\067" +
    "\053\064\054\075\001\002\000\020\005\052\016\057\021" +
    "\072\035\055\037\067\053\064\054\075\001\002\000\020" +
    "\005\052\016\057\021\072\035\055\037\067\053\064\054" +
    "\075\001\002\000\020\005\052\016\057\021\072\035\055" +
    "\037\067\053\064\054\075\001\002\000\066\005\uffc6\011" +
    "\uffc6\012\uffc6\014\uffc6\015\uffc6\016\uffc6\017\uffc6\021\uffc6" +
    "\022\uffc6\025\uffc6\026\uffc6\034\uffc6\035\uffc6\036\uffc6\037" +
    "\uffc6\040\uffc6\042\uffc6\043\uffc6\044\uffc6\045\uffc6\046\100" +
    "\047\102\050\101\051\077\053\uffc6\054\uffc6\001\002\000" +
    "\066\005\uffc7\011\uffc7\012\uffc7\014\uffc7\015\uffc7\016\uffc7" +
    "\017\uffc7\021\uffc7\022\uffc7\025\uffc7\026\uffc7\034\uffc7\035" +
    "\uffc7\036\uffc7\037\uffc7\040\uffc7\042\uffc7\043\uffc7\044\uffc7" +
    "\045\uffc7\046\uffc7\047\uffc7\050\uffc7\051\uffc7\053\uffc7\054" +
    "\uffc7\001\002\000\066\005\uffc4\011\uffc4\012\uffc4\014\uffc4" +
    "\015\uffc4\016\uffc4\017\uffc4\021\uffc4\022\uffc4\025\uffc4\026" +
    "\uffc4\034\uffc4\035\uffc4\036\uffc4\037\uffc4\040\uffc4\042\uffc4" +
    "\043\uffc4\044\uffc4\045\uffc4\046\100\047\102\050\101\051" +
    "\077\053\uffc4\054\uffc4\001\002\000\066\005\uffc8\011\uffc8" +
    "\012\uffc8\014\uffc8\015\uffc8\016\uffc8\017\uffc8\021\uffc8\022" +
    "\uffc8\025\uffc8\026\uffc8\034\uffc8\035\uffc8\036\uffc8\037\uffc8" +
    "\040\uffc8\042\uffc8\043\uffc8\044\uffc8\045\uffc8\046\uffc8\047" +
    "\uffc8\050\uffc8\051\uffc8\053\uffc8\054\uffc8\001\002\000\066" +
    "\005\uffc3\011\uffc3\012\uffc3\014\uffc3\015\uffc3\016\uffc3\017" +
    "\uffc3\021\uffc3\022\uffc3\025\uffc3\026\uffc3\034\uffc3\035\uffc3" +
    "\036\uffc3\037\uffc3\040\uffc3\042\uffc3\043\uffc3\044\uffc3\045" +
    "\uffc3\046\100\047\102\050\101\051\077\053\uffc3\054\uffc3" +
    "\001\002\000\020\005\052\016\057\021\072\035\055\037" +
    "\067\053\064\054\075\001\002\000\024\005\052\016\057" +
    "\021\072\035\055\036\ufffd\037\067\042\113\053\064\054" +
    "\075\001\002\000\020\005\052\016\057\021\072\035\055" +
    "\037\067\053\064\054\075\001\002\000\036\005\052\016" +
    "\057\021\072\034\103\035\055\036\ufffd\037\067\042\113" +
    "\046\100\047\102\050\101\051\077\053\064\054\075\001" +
    "\002\000\004\036\uffbc\001\002\000\004\036\117\001\002" +
    "\000\066\005\uffbf\011\uffbf\012\uffbf\014\uffbf\015\uffbf\016" +
    "\uffbf\017\uffbf\021\uffbf\022\uffbf\025\uffbf\026\uffbf\034\uffbf" +
    "\035\uffbf\036\uffbf\037\uffbf\040\uffbf\042\uffbf\043\uffbf\044" +
    "\uffbf\045\uffbf\046\uffbf\047\uffbf\050\uffbf\051\uffbf\053\uffbf" +
    "\054\uffbf\001\002\000\004\036\uffbe\001\002\000\036\005" +
    "\052\016\057\021\072\034\103\035\055\036\ufffd\037\067" +
    "\042\113\046\100\047\102\050\101\051\077\053\064\054" +
    "\075\001\002\000\004\036\uffbd\001\002\000\016\034\103" +
    "\040\124\046\100\047\102\050\101\051\077\001\002\000" +
    "\066\005\uffc0\011\uffc0\012\uffc0\014\uffc0\015\uffc0\016\uffc0" +
    "\017\uffc0\021\uffc0\022\uffc0\025\uffc0\026\uffc0\034\uffc0\035" +
    "\uffc0\036\uffc0\037\uffc0\040\uffc0\042\uffc0\043\uffc0\044\uffc0" +
    "\045\uffc0\046\uffc0\047\uffc0\050\uffc0\051\uffc0\053\uffc0\054" +
    "\uffc0\001\002\000\016\034\103\043\126\046\100\047\102" +
    "\050\101\051\077\001\002\000\034\005\uffb2\012\uffb2\015" +
    "\uffb2\016\uffb2\017\uffb2\021\uffb2\022\uffb2\025\uffb2\026\uffb2" +
    "\035\uffb2\037\uffb2\053\uffb2\054\uffb2\001\002\000\016\034" +
    "\103\040\130\046\100\047\102\050\101\051\077\001\002" +
    "\000\066\005\uffc2\011\uffc2\012\uffc2\014\uffc2\015\uffc2\016" +
    "\uffc2\017\uffc2\021\uffc2\022\uffc2\025\uffc2\026\uffc2\034\uffc2" +
    "\035\uffc2\036\uffc2\037\uffc2\040\uffc2\042\uffc2\043\uffc2\044" +
    "\uffc2\045\uffc2\046\uffc2\047\uffc2\050\uffc2\051\uffc2\053\uffc2" +
    "\054\uffc2\001\002\000\020\005\052\016\057\021\072\035" +
    "\055\037\067\053\141\054\075\001\002\000\020\005\052" +
    "\016\057\021\072\035\055\037\067\053\064\054\075\001" +
    "\002\000\024\005\052\016\057\021\072\035\055\036\ufffd" +
    "\037\067\042\113\053\064\054\075\001\002\000\004\036" +
    "\135\001\002\000\050\005\uffbf\012\uffbf\015\uffbf\016\uffbf" +
    "\017\uffbf\021\uffbf\022\uffbf\025\uffbf\026\uffbf\034\uffbf\035" +
    "\uffbf\037\uffbf\043\136\046\uffbf\047\uffbf\050\uffbf\051\uffbf" +
    "\053\uffbf\054\uffbf\001\002\000\034\005\uffa8\012\uffa8\015" +
    "\uffa8\016\uffa8\017\uffa8\021\uffa8\022\uffa8\025\uffa8\026\uffa8" +
    "\035\uffa8\037\uffa8\053\uffa8\054\uffa8\001\002\000\016\034" +
    "\103\043\140\046\100\047\102\050\101\051\077\001\002" +
    "\000\034\005\uffb1\012\uffb1\015\uffb1\016\uffb1\017\uffb1\021" +
    "\uffb1\022\uffb1\025\uffb1\026\uffb1\035\uffb1\037\uffb1\053\uffb1" +
    "\054\uffb1\001\002\000\016\034\uffcb\040\142\046\uffcb\047" +
    "\uffcb\050\uffcb\051\uffcb\001\002\000\004\052\143\001\002" +
    "\000\020\005\052\016\057\021\072\035\055\037\067\053" +
    "\064\054\075\001\002\000\016\034\103\043\145\046\100" +
    "\047\102\050\101\051\077\001\002\000\034\005\uffb0\012" +
    "\uffb0\015\uffb0\016\uffb0\017\uffb0\021\uffb0\022\uffb0\025\uffb0" +
    "\026\uffb0\035\uffb0\037\uffb0\053\uffb0\054\uffb0\001\002\000" +
    "\024\005\052\016\057\021\072\035\055\036\151\037\067" +
    "\053\064\054\152\055\147\001\002\000\004\036\160\001" +
    "\002\000\016\034\103\036\156\046\100\047\102\050\101" +
    "\051\077\001\002\000\004\043\155\001\002\000\022\034" +
    "\uffcc\035\112\036\153\037\111\046\uffcc\047\uffcc\050\uffcc" +
    "\051\uffcc\001\002\000\004\043\154\001\002\000\034\005" +
    "\uffac\012\uffac\015\uffac\016\uffac\017\uffac\021\uffac\022\uffac" +
    "\025\uffac\026\uffac\035\uffac\037\uffac\053\uffac\054\uffac\001" +
    "\002\000\034\005\uffa9\012\uffa9\015\uffa9\016\uffa9\017\uffa9" +
    "\021\uffa9\022\uffa9\025\uffa9\026\uffa9\035\uffa9\037\uffa9\053" +
    "\uffa9\054\uffa9\001\002\000\004\043\157\001\002\000\034" +
    "\005\uffab\012\uffab\015\uffab\016\uffab\017\uffab\021\uffab\022" +
    "\uffab\025\uffab\026\uffab\035\uffab\037\uffab\053\uffab\054\uffab" +
    "\001\002\000\004\043\161\001\002\000\034\005\uffaa\012" +
    "\uffaa\015\uffaa\016\uffaa\017\uffaa\021\uffaa\022\uffaa\025\uffaa" +
    "\026\uffaa\035\uffaa\037\uffaa\053\uffaa\054\uffaa\001\002\000" +
    "\016\014\163\034\103\046\100\047\102\050\101\051\077" +
    "\001\002\000\004\044\164\001\002\000\034\005\052\012" +
    "\071\015\063\016\057\017\ufffd\021\072\022\056\025\062" +
    "\026\ufffd\035\055\037\067\053\064\054\066\001\002\000" +
    "\006\017\166\026\167\001\002\000\004\025\175\001\002" +
    "\000\004\044\170\001\002\000\032\005\052\012\071\015" +
    "\063\016\057\017\ufffd\021\072\022\056\025\062\035\055" +
    "\037\067\053\064\054\066\001\002\000\004\017\172\001" +
    "\002\000\004\025\173\001\002\000\004\043\174\001\002" +
    "\000\034\005\uffae\012\uffae\015\uffae\016\uffae\017\uffae\021" +
    "\uffae\022\uffae\025\uffae\026\uffae\035\uffae\037\uffae\053\uffae" +
    "\054\uffae\001\002\000\004\043\176\001\002\000\034\005" +
    "\uffaf\012\uffaf\015\uffaf\016\uffaf\017\uffaf\021\uffaf\022\uffaf" +
    "\025\uffaf\026\uffaf\035\uffaf\037\uffaf\053\uffaf\054\uffaf\001" +
    "\002\000\006\017\uffb4\026\uffb4\001\002\000\016\011\201" +
    "\034\103\046\100\047\102\050\101\051\077\001\002\000" +
    "\020\005\052\016\057\021\072\035\055\037\067\053\064" +
    "\054\075\001\002\000\016\034\103\045\203\046\100\047" +
    "\102\050\101\051\077\001\002\000\020\005\052\016\057" +
    "\021\072\035\055\037\067\053\064\054\075\001\002\000" +
    "\016\034\103\044\205\046\100\047\102\050\101\051\077" +
    "\001\002\000\032\005\052\012\071\015\063\016\057\017" +
    "\ufffd\021\072\022\056\025\062\035\055\037\067\053\064" +
    "\054\066\001\002\000\004\017\207\001\002\000\004\022" +
    "\210\001\002\000\004\043\211\001\002\000\034\005\uffad" +
    "\012\uffad\015\uffad\016\uffad\017\uffad\021\uffad\022\uffad\025" +
    "\uffad\026\uffad\035\uffad\037\uffad\053\uffad\054\uffad\001\002" +
    "\000\016\034\103\036\213\046\100\047\102\050\101\051" +
    "\077\001\002\000\066\005\uffc1\011\uffc1\012\uffc1\014\uffc1" +
    "\015\uffc1\016\uffc1\017\uffc1\021\uffc1\022\uffc1\025\uffc1\026" +
    "\uffc1\034\uffc1\035\uffc1\036\uffc1\037\uffc1\040\uffc1\042\uffc1" +
    "\043\uffc1\044\uffc1\045\uffc1\046\uffc1\047\uffc1\050\uffc1\051" +
    "\uffc1\053\uffc1\054\uffc1\001\002\000\004\041\215\001\002" +
    "\000\004\002\ufffe\001\002\000\010\042\216\044\ufffd\054" +
    "\220\001\002\000\004\044\224\001\002\000\010\042\216" +
    "\044\ufffd\054\220\001\002\000\006\006\uffe0\027\uffe0\001" +
    "\002\000\004\044\uffdb\001\002\000\004\044\uffdd\001\002" +
    "\000\010\004\045\013\046\054\226\001\002\000\004\043" +
    "\230\001\002\000\016\031\uffd9\036\uffd9\042\uffd9\043\uffd9" +
    "\044\uffd9\054\uffd9\001\002\000\016\031\uffda\036\uffda\042" +
    "\uffda\043\uffda\044\uffda\054\uffda\001\002\000\014\006\uffde" +
    "\027\uffde\042\216\044\ufffd\054\220\001\002\000\006\006" +
    "\uffdf\027\uffdf\001\002\000\004\044\uffdc\001\002\000\004" +
    "\006\ufff2\001\002\000\010\006\uffd5\020\235\023\237\001" +
    "\002\000\004\054\271\001\002\000\004\006\uffd8\001\002" +
    "\000\004\054\242\001\002\000\010\006\uffd4\020\235\023" +
    "\237\001\002\000\004\006\uffd6\001\002\000\004\035\243" +
    "\001\002\000\016\031\244\036\ufffd\042\216\043\246\044" +
    "\ufffd\054\220\001\002\000\010\042\216\044\ufffd\054\220" +
    "\001\002\000\004\044\264\001\002\000\012\031\244\042" +
    "\216\044\ufffd\054\220\001\002\000\004\036\253\001\002" +
    "\000\016\031\244\036\ufffd\042\216\043\246\044\ufffd\054" +
    "\220\001\002\000\006\036\uffcd\044\uffdb\001\002\000\004" +
    "\036\uffcf\001\002\000\004\044\254\001\002\000\014\006" +
    "\ufffd\007\013\027\014\030\022\032\017\001\002\000\004" +
    "\006\256\001\002\000\032\005\052\012\071\015\063\016" +
    "\057\017\ufffd\021\072\022\056\025\062\035\055\037\067" +
    "\053\064\054\066\001\002\000\004\017\260\001\002\000" +
    "\004\043\261\001\002\000\010\006\uffd3\020\uffd3\023\uffd3" +
    "\001\002\000\016\031\244\036\ufffd\042\216\043\246\044" +
    "\ufffd\054\220\001\002\000\004\036\uffce\001\002\000\006" +
    "\004\045\013\046\001\002\000\016\031\uffd0\036\uffd0\042" +
    "\uffd0\043\uffd0\044\uffd0\054\uffd0\001\002\000\004\044\267" +
    "\001\002\000\010\004\045\013\046\054\226\001\002\000" +
    "\016\031\uffd1\036\uffd1\042\uffd1\043\uffd1\044\uffd1\054\uffd1" +
    "\001\002\000\004\035\272\001\002\000\016\031\244\036" +
    "\ufffd\042\216\043\246\044\ufffd\054\220\001\002\000\004" +
    "\036\274\001\002\000\004\044\275\001\002\000\006\004" +
    "\045\013\046\001\002\000\004\044\277\001\002\000\014" +
    "\006\ufffd\007\013\027\014\030\022\032\017\001\002\000" +
    "\004\006\301\001\002\000\032\005\052\012\071\015\063" +
    "\016\057\017\ufffd\021\072\022\056\025\062\035\055\037" +
    "\067\053\064\054\066\001\002\000\004\017\303\001\002" +
    "\000\004\043\304\001\002\000\010\006\uffd2\020\uffd2\023" +
    "\uffd2\001\002\000\004\006\uffd7\001\002\000\012\006\uffec" +
    "\027\uffec\030\uffec\032\uffec\001\002\000\004\052\310\001" +
    "\002\000\010\005\313\016\314\053\312\001\002\000\004" +
    "\043\315\001\002\000\004\043\uffe9\001\002\000\004\043" +
    "\uffe8\001\002\000\004\043\uffe7\001\002\000\014\006\uffea" +
    "\027\uffea\030\uffea\032\uffea\054\307\001\002\000\012\006" +
    "\uffeb\027\uffeb\030\uffeb\032\uffeb\001\002\000\010\006\ufff7" +
    "\027\014\032\017\001\002\000\004\006\ufff5\001\002\000" +
    "\006\006\ufff6\027\014\001\002\000\004\006\ufff9\001\002" +
    "\000\004\006\ufffa\001\002\000\006\006\ufffb\027\014\001" +
    "\002\000\004\006\ufffc\001\002\000\004\002\001\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\324\000\006\002\003\041\004\001\001\000\002\001" +
    "\001\000\004\003\005\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\016\004\020\005\017\006" +
    "\011\011\022\015\015\021\014\001\001\000\010\011\316" +
    "\015\320\021\317\001\001\000\004\007\305\001\001\000" +
    "\010\022\235\023\233\024\237\001\001\000\002\001\001" +
    "\000\004\021\232\001\001\000\010\004\221\016\220\017" +
    "\216\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\012\027\001\001\000\006\015\024\021\023\001\001\000" +
    "\002\001\001\000\004\021\025\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\014\032\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\012\034" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\013\043\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\026\004\073\027\064\030\053" +
    "\032\057\033\050\034\052\035\047\036\072\037\060\040" +
    "\067\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\030" +
    "\211\001\001\000\004\030\177\001\001\000\002\001\001" +
    "\000\026\004\073\027\064\030\053\032\057\033\176\034" +
    "\052\035\047\036\072\037\060\040\067\001\001\000\002" +
    "\001\001\000\004\030\161\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\030\126\001\001\000\002\001\001\000\004\030\124\001" +
    "\001\000\004\030\075\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\030" +
    "\107\001\001\000\004\030\106\001\001\000\004\030\105" +
    "\001\001\000\004\030\104\001\001\000\004\030\103\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\030\122\001" +
    "\001\000\010\004\114\030\113\031\115\001\001\000\004" +
    "\030\120\001\001\000\010\004\114\030\113\031\117\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\004\114\030\113\031\121\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\030\122\001\001\000\004\030\136" +
    "\001\001\000\010\004\114\030\113\031\133\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\030\143\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\030\147\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\026\004\073\027" +
    "\064\030\053\032\057\033\164\034\052\035\047\036\072" +
    "\037\060\040\067\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\026\004\073\027\064\030\053" +
    "\032\057\033\170\034\052\035\047\036\072\037\060\040" +
    "\067\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\030\201" +
    "\001\001\000\002\001\001\000\004\030\203\001\001\000" +
    "\002\001\001\000\026\004\073\027\064\030\053\032\057" +
    "\033\205\034\052\035\047\036\072\037\060\040\067\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\004\221\017\231" +
    "\001\001\000\002\001\001\000\006\004\221\017\222\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\013\226\020\224\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\004\221\016\230" +
    "\017\216\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\022\304\023\233\024\237\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\022\240\023\233\024\237\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\004\250\017\244\025\247\026" +
    "\246\001\001\000\006\004\221\017\265\001\001\000\002" +
    "\001\001\000\010\004\221\017\244\025\261\001\001\000" +
    "\002\001\001\000\012\004\250\017\244\025\247\026\251" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\016\004\020\005\254\006\011\011\022\015\015" +
    "\021\014\001\001\000\002\001\001\000\026\004\073\027" +
    "\064\030\053\032\057\033\256\034\052\035\047\036\072" +
    "\037\060\040\067\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\004\250\017\244\025\247" +
    "\026\262\001\001\000\002\001\001\000\004\013\264\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\013\226" +
    "\020\267\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\004\250\017\244\025\247\026\272\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\013\275\001\001\000" +
    "\002\001\001\000\016\004\020\005\277\006\011\011\022" +
    "\015\015\021\014\001\001\000\002\001\001\000\026\004" +
    "\073\027\064\030\053\032\057\033\301\034\052\035\047" +
    "\036\072\037\060\040\067\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\310\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\007\315\001\001\000\002\001\001\000" +
    "\006\015\323\021\322\001\001\000\002\001\001\000\004" +
    "\021\321\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\021\324\001\001\000\002\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




	SyntaxErrorManager syntaxErrorManager = CompilerContext.getSyntaxErrorManager();
	
	public void syntax_error(Symbol symbol)
	{ 
	    Token token = (Token) symbol.value;
	    syntaxErrorManager.syntaxError ("Error sintactico", token);	    
	}
		
	public void unrecovered_syntax_error(java_cup.runtime.Symbol symbol)
	{	
	    Token token = (Token) symbol.value;
	    syntaxErrorManager.syntaxFatalError ("Error fatal", token);
	}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {


	
	SyntaxErrorManager   syntaxErrorManager   = CompilerContext.getSyntaxErrorManager();
	SemanticErrorManager semanticErrorManager = CompilerContext.getSemanticErrorManager ();
	ScopeManagerIF       scopeManager         = CompilerContext.getScopeManager ();
	FinalCodeFactoryIF   finalCodeFactory     = CompilerContext.getFinalCodeFactory ();


  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // sentenciaLlamada ::= IDENTIFICADOR PARIZQ listaExpresiones PARDER PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaLlamada",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // sentenciaSalida ::= ESCRIBIR PARIZQ PARDER PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaSalida",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // sentenciaSalida ::= ESCRIBIR PARIZQ CADENA PARDER PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaSalida",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // sentenciaSalida ::= ESCRIBIR PARIZQ expresion PARDER PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaSalida",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // sentenciaSalida ::= ESCRIBIR PARIZQ IDENTIFICADOR PARDER PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaSalida",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // sentenciaPara ::= PARA expresion EN expresion RANGO expresion DOSPUNTOS listaSentencias FIN PARA PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaPara",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // sentenciaSi ::= SI expresion ENTONCES DOSPUNTOS listaSentencias SINO DOSPUNTOS listaSentencias FIN SI PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaSi",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // sentenciaSi ::= SI expresion ENTONCES DOSPUNTOS listaSentencias FIN SI PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaSi",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // sentenciaAsignacion ::= IDENTIFICADOR CORIZQ NUMERO CORDER ASIGNACION expresion PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaAsignacion",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // sentenciaAsignacion ::= IDENTIFICADOR ASIGNACION expresion PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaAsignacion",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // retorno ::= DEVOLVER expresion PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("retorno",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // listaSentencias ::= epsilon 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaSentencias",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // listaSentencias ::= sentencia listaSentencias 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaSentencias",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // sentencia ::= sentenciaLlamada 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // sentencia ::= sentenciaSalida 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // sentencia ::= sentenciaPara 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // sentencia ::= sentenciaSi 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // sentencia ::= sentenciaAsignacion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // sentencia ::= retorno 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // sentencia ::= expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // listaExpresiones ::= epsilon 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaExpresiones",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // listaExpresiones ::= COMA expresion listaExpresiones 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaExpresiones",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // listaExpresiones ::= expresion listaExpresiones 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaExpresiones",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expresion ::= IDENTIFICADOR PARIZQ listaExpresiones PARDER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expresion ::= IDENTIFICADOR CORIZQ expresion CORDER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expresion ::= PARIZQ expresion PARDER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expresion ::= CORIZQ expresion CORDER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expresion ::= expresion IGUAL expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expresion ::= expresion MENOR expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expresion ::= NO expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expresion ::= expresion Y expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expresion ::= expresion PRODUCTO expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expresion ::= expresion SUMA expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expresion ::= FALSO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expresion ::= CIERTO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expresion ::= NUMERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expresion ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // listaParametros ::= epsilon 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaParametros",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // listaParametros ::= PUNTOYCOMA parametros listaParametros 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaParametros",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // listaParametros ::= parametros listaParametros 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaParametros",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // parametros ::= listaIdentificadores DOSPUNTOS tiposPrimitivos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametros",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // parametros ::= VAR listaIdentificadores DOSPUNTOS tiposVariables 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametros",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // declaracionFuncion ::= FUNCION IDENTIFICADOR PARIZQ listaParametros PARDER DOSPUNTOS tiposPrimitivos DOSPUNTOS opcionales COMIENZO listaSentencias FIN PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionFuncion",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-12)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // declaracionProcedimiento ::= PROCEDIMIENTO IDENTIFICADOR PARIZQ listaParametros PARDER DOSPUNTOS opcionales COMIENZO listaSentencias FIN PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionProcedimiento",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // declaracionSubprogramas ::= declaracionFuncion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprogramas",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // declaracionSubprogramas ::= declaracionProcedimiento 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprogramas",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // declaracionSubprogramas ::= declaracionFuncion declaracionSubprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprogramas",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // declaracionSubprogramas ::= declaracionProcedimiento declaracionSubprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprogramas",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // seccionSubprogramas ::= SUBPROGRAMAS declaracionSubprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionSubprogramas",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // tiposVariables ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tiposVariables",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // tiposVariables ::= tiposPrimitivos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tiposVariables",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // listaIdentificadores ::= epsilon 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaIdentificadores",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // listaIdentificadores ::= COMA listaIdentificadores 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaIdentificadores",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // listaIdentificadores ::= IDENTIFICADOR listaIdentificadores 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaIdentificadores",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // declaracionVariables ::= listaIdentificadores DOSPUNTOS tiposVariables PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVariables",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // declaracionVariables ::= listaIdentificadores DOSPUNTOS tiposVariables PUNTOYCOMA declaracionVariables 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVariables",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // seccionVariables ::= VARIABLES declaracionVariables 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionVariables",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // tiposCompuestos ::= VECTOR CORIZQ NUMERO RANGO NUMERO CORDER DE tiposPrimitivos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tiposCompuestos",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // tiposPrimitivos ::= BOOLEANO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tiposPrimitivos",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // tiposPrimitivos ::= ENTERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tiposPrimitivos",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // declaracionTipos ::= IDENTIFICADOR ASIGNACION tiposCompuestos PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionTipos",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // declaracionTipos ::= IDENTIFICADOR ASIGNACION tiposCompuestos PUNTOYCOMA declaracionTipos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionTipos",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // seccionTipos ::= TIPOS declaracionTipos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionTipos",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // tiposConstante ::= FALSO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tiposConstante",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // tiposConstante ::= CIERTO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tiposConstante",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tiposConstante ::= NUMERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tiposConstante",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // declaracionConstantes ::= IDENTIFICADOR ASIGNACION tiposConstante PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionConstantes",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // declaracionConstantes ::= IDENTIFICADOR ASIGNACION tiposConstante PUNTOYCOMA declaracionConstantes 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionConstantes",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // seccionConstantes ::= CONSTANTES declaracionConstantes 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionConstantes",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // opcionales ::= epsilon 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opcionales",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // opcionales ::= seccionSubprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opcionales",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // opcionales ::= seccionVariables 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opcionales",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // opcionales ::= seccionTipos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opcionales",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // opcionales ::= seccionConstantes 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opcionales",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // opcionales ::= seccionVariables seccionSubprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opcionales",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // opcionales ::= seccionTipos seccionSubprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opcionales",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // opcionales ::= seccionTipos seccionVariables 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opcionales",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // opcionales ::= seccionConstantes seccionSubprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opcionales",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // opcionales ::= seccionConstantes seccionVariables 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opcionales",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // opcionales ::= seccionConstantes seccionTipos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opcionales",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // opcionales ::= seccionTipos seccionVariables seccionSubprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opcionales",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // opcionales ::= seccionConstantes seccionVariables seccionSubprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opcionales",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // opcionales ::= seccionConstantes seccionTipos seccionSubprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opcionales",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // opcionales ::= seccionConstantes seccionTipos seccionVariables 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opcionales",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // opcionales ::= seccionConstantes seccionTipos seccionVariables seccionSubprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opcionales",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // epsilon ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("epsilon",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // axiom ::= PROGRAMA IDENTIFICADOR DOSPUNTOS opcionales COMIENZO listaSentencias FIN PUNTO 
            {
              Axiom RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= NT$0 axiom 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int axleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int axright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Axiom ax = (Axiom)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
  		// No modificar esta estructura, aunque se pueden añadir más acciones semánticas
  		// Para la entrega de febrero pueden comentarse las dos sentencias siguientes:
  		//List intermediateCode = ax.getIntermediateCode ();
  		//finalCodeFactory.create (intermediateCode);
  		// En caso de no comentarse las sentencias anteriores puede generar una excepcion
  		// en las llamadas a cupTest en la entrega de Febrero. Esto es debido a que 
  		// aún no se tendrá implementada la generación de código intermedio ni final.
  		// Para la entrega de Junio deberán descomentarse y usarse.
  		
  		syntaxErrorManager.syntaxInfo ("Parsing process ended.");
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // NT$0 ::= 
            {
              Object RESULT =null;
 
        syntaxErrorManager.syntaxInfo ("Starting parsing..."); 
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

